name: Prepare
inputs:
  branch:
    type: string
runs:
  using: "composite"
  steps:
      - if: ${{ inputs.branch != '' }}
        run: git checkout ${{ inputs.branch }}
        shell: bash
      - run: git fetch --tags origin
        shell: bash
      - run: git submodule sync
        shell: bash
      - run: git submodule update --init --recursive
        shell: bash
