name: CI

on:
  workflow_call:
    inputs:
      branch:
        type: string
      repo:
        type: string
      tree:
        required: true
        type: string

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Test environment
        run: ./.ci.sh test-environment

      - name: Checkout branch
        if: ${{ inputs.branch != '' }}
        run: ./.ci.sh checkout-branch ${{ inputs.branch }}

      - name: Update submodules
        run: ./.ci.sh update-submodules

      - name: Build tree
        run: ./.ci.sh build-tree ${{ inputs.tree }} ${{ inputs.repo }}
