on:
  push:
    branches:
      - release/current
      - release/long/4
      - release/next
      - test-github-actions

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: echo ${GITHUB_REF##*/}

      - name: Update submodules
        run: ./.ci.sh update-submodules ${GITHUB_REF##*/}
