name: "Update (Scheduled)"

on:
  schedule:
    - cron: '0 4 * * 3,6' # At 04:00 on Wednesday and Saturday
  workflow_dispatch:

jobs:
  desktop--current:
    name: "Desktop (Current)"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          branch: release/current
      - uses: ./.github/actions/build
        with:
          tree: desktop
  desktop--long-4:
    name: "Desktop (Long 4)"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          branch: release/long/4
      - uses: ./.github/actions/build
        with:
          tree: desktop
  desktop--next:
    name: "Desktop (Next)"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
        with:
          branch: release/next
      - uses: ./.github/actions/build
        with:
          tree: desktop
